FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
EXPOSE 4200
# IMPORTANT: on utilise un proxy Angular pour /api (cf. fichier ci-dessous)
CMD ["npm","run","start","--","--host","0.0.0.0","--port","4200","--proxy-config","proxy.docker.json"]
